name: bava
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.16.0
  - comm=0.1.2
  - cryptography=41.0.3
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.5.0
  - gettext=0.21.0
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - iniconfig=1.1.1
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jupyter=1.0.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - krb5=1.20.1
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcxx=14.0.6
  - libedit=3.1.20221030
  - libffi=3.4.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mysql=5.7.24
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - openssl=3.2.0
  - overrides=7.4.0
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=1.10.13
  - pyopenssl=23.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qtconsole=5.5.0
  - qtpy=2.4.1
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - starlette=0.27.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==3.7.1
      - blinker==1.7.0
      - cachetools==5.3.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - fastapi==0.104.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - greenlet==3.0.1
      - h11==0.14.0
      - httptools==0.6.1
      - idna==3.6
      - importlib-metadata==6.9.0
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - numpy==1.26.2
      - pandas==2.1.3
      - pillow==10.1.0
      - protobuf==4.25.1
      - pyarrow==14.0.1
      - pydantic-core==2.14.5
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - python-dotenv==1.0.0
      - referencing==0.31.1
      - rich==13.7.0
      - rpds-py==0.13.2
      - smmap==5.0.1
      - sniffio==1.3.0
      - sqlalchemy==2.0.23
      - sqlmodel==0.0.12
      - streamlit==1.29.0
      - tenacity==8.2.3
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.4
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - tzlocal==5.2
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - validators==0.22.0
      - watchfiles==0.21.0
      - websockets==12.0
      - zipp==3.17.0
